[env:d1_mini_pro]
platform = espressif8266
board = d1_mini_pro
framework = arduino

board_build.flash_mode = dout

monitor_port = COM9
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library
    arduino-libraries/ArduinoMqttClient